### ISSUE TITLE
Total Run Time always at 0

### ISSUE THREAD

**Issue by caesartcs** [hashview/hashview#306] opened 2017-06-05 17:59 UTC
[Ubuntu Desktop 14.04 LTS]
[Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jun 05 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux]

I love this app, I got it to work and crack passwords.
However, I always get 0 for `Total Run Time`, whether I crack an individual hash or a file full of hashes.

This happens on all hash types too (although **md5** and **ntlmv2** is what I mostly crack)

Please let me know if there is something within the installation process I might have looked over.
Thanks

**Comment by caesartcs** [comment] 2017-06-15 17:57
After some further looking, I believe the Time Function is failing because of the `sinatra` gem.
I am currently running `sinatra 1.4.7`
Ill update if I see anything

Ref: #290

**Comment by i128** [comment] 2017-06-20 17:57
This issue was caused by the introduction of the background worker. It will be fixed in version v0.7.0

**Comment by caesartcs** [comment] 2017-06-21 13:55
@i128 Dont want to be annoying, but is there an ETA on v0.7.0?

Thank you!

**Comment by i128** [comment] 2017-06-21 14:27
There's still a lot of bugs to workout, no official ETA, but our goal is to have it ready for Blackhat, so late July.

**Comment by caesartcs** [comment] 2017-06-21 19:29
Cool thank you for this project. And keep up the good work, you guys are amazing! @i128 @ccammilleri

**Comment by ccammilleri** [comment] 2017-07-23 04:59
0.7 has landed today. fixed!

**Closed by ccammilleri** 2017-07-23 04:59 UTC
Labels: bug
