### ISSUE TITLE
Downloading cracked file results in internal error

### ISSUE THREAD

**Issue by comanche86** [hashview/hashview#152] opened 2016-10-06 21:14 UTC
Opening analytics and going to _Download Cracked File_

URL: https://SERVER:4567/download?custid=2

Results in _Internal Server Error_

The error output is below

`^[2016-10-06 16:11:16 - NoMethodError - undefined method `+' for nil:NilClass:
        main.rb:1114:in `block (3 levels) in <main>'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/collection.rb:50
8:in `block in each'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_arr
ay.rb:411:in `block in each'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_arr
ay.rb:411:in `each'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
        main.rb:1113:in `block (2 levels) in <main>'
        main.rb:1112:in `open'
        main.rb:1112:in `block in <main>'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /home/useraccount/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /home/useraccount/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /home/useraccount/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /home/useraccount/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
10.110.5.12 - - [06/Oct/2016:16:11:16 -0500] "GET /download?custid=2 HTTP/1.1" 500 30 0.0403
10.110.5.12 - - [06/Oct/2016:16:11:16 CDT] "GET /download?custid=2 HTTP/1.1" 500 30
https://SERVER:4567/analytics?custid=2 -> /download?custid=2
10.110.5.12 - - [06/Oct/2016:16:11:20 -0500] "GET /analytics?custid=2 HTTP/1.1" 200 20858 0.0981
10.110.5.12 - - [06/Oct/2016:16:11:20 CDT] "GET /analytics?custid=2 HTTP/1.1" 200 20858
https://SERVER:4567/analytics?custid=5 -> /analytics?custid=2
sh: 1: nvidia-settings: not found
`

**Comment by i128** [comment] 2016-10-06 21:17
How many total customers do you have?

**Comment by comanche86** [comment] 2016-10-06 21:22
4 total - 7 hashfiles between them

**Comment by i128** [comment] 2016-10-06 21:26
If possible, log into your database and run the following command and let me know the output:

  use hashview;
  select count(*) from targets where customer_id = '2';

**Comment by comanche86** [comment] 2016-10-06 21:35
Sure thing

count(*) 1,659

**Comment by i128** [comment] 2016-10-06 21:44
Shoot, okay.  I think i know where the problem is. Give me a bit and i'll reply back here once a fix is in place.

**Comment by comanche86** [comment] 2016-10-06 21:46
Awesome, thank you!!

**Comment by i128** [comment] 2016-10-06 23:44
@comanche86 , i just committed a change to the dev branch of hashview. Can you check it out and see if it resolves the issue for you. I tested it locally and both a) reproduced the issue before the fix, and b) validated that it is resolved with my test data.

**Comment by comanche86** [comment] 2016-10-09 00:07
Still looks like the same error unfortunately.

I did notice something else though. The customer I'm downloading the file for, has cracked hashes and I can't download the file.

However, I can download the file for other customers that **do not** have cracked hashes.

**Comment by i128** [comment] 2016-10-09 01:38
Hm, I wonder if there are any empty/null entries in the DB (which is what the error message seems to indicate). The dev branch should have fixed for this in the commit a few days ago.

Can you check by running the following:
SELECT COUNT(*) FROM targets where customer_id = 2 and (CHAR_LENGTH(username) < 1 or plaintext is NULL);
SELECT COUNT(*) FROM targets where customer_id = 2 and (CHAR_LENGTH(originalhash) < 1 or plaintext is NULL);
SELECT COUNT(*) FROM targets where customer_id = 2 and (CHAR_LENGTH(plaintext) < 1 or plaintext is NULL);

**Comment by comanche86** [comment] 2016-10-09 22:15
Sure thing,

Looks like 1,041 for all three

Looking at the targets list there are a lot of null for plaintext and the username field is null (this should be the case though, I just fed it pw hashes)

**Comment by i128** [comment] 2016-10-09 23:04
Can you copy/paste the most recent error message. With the attempted fix on 10-6-2016. The line numbers will be different from your initial attempt.

**Comment by comanche86** [comment] 2016-10-09 23:12
Sure thing, see below. I'm using the dev branch, I haven't rebuilt the DB though.

`https://SERVER:4567/analytics?custid=2 -> /analytics/graph3?custid=2&hf_id=
2016-10-09 18:08:37 - NoMethodError - undefined method `+' for nil:NilClass:
        main.rb:1114:in `block (3 levels) in <main>'
        /home/user/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/collection.rb:508:in `block in each'
        /home/user/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `block in each'
        /home/user/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
        /home/user/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
        /home/user/.rvm/gems/ruby-2.2.2/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
        main.rb:1113:in `block (2 levels) in <main>'
        main.rb:1112:in `open'
        main.rb:1112:in `block in <main>'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
10.110.5.12 - - [09/Oct/2016:18:08:37 -0500] "GET /download?custid=2 HTTP/1.1" 500 30 0.0395
10.110.5.12 - - [09/Oct/2016:18:08:37 CDT] "GET /download?custid=2 HTTP/1.1" 500 30
https://SERVER:4567/analytics?custid=2 -> /download?custid=2
`

**Comment by i128** [comment] 2016-10-09 23:19
Can you do a:

git branch -v

It looks like the error is refrencing line 1113 in main.rb with "open".  however, the open isnt listed in that function. 

did you do a 

git pull origin dev

to update your local copy?

Good news is that you should not need to make any changes to your DB for this fix

**Comment by comanche86** [comment] 2016-10-09 23:28
Welp I'm an idiot... for some reason I pulled down the master instead of the dev.

At any rate, got the dev version and it's definitely working now :)

**Comment by i128** [comment] 2016-10-09 23:31
Wooo awesome! Thanks for reporting the issue and testing the fix.  We'll be
pushing dev to master here soon. In the meantime let us know if you
encounter any further errors/problems

**Comment by comanche86** [comment] 2016-10-09 23:31
Definitely! Thank you!

**Comment by i128** [comment] 2016-10-18 18:37
Issue should be corrected in release v0.4-beta

**Closed by i128** 2016-10-18 18:37 UTC
Labels: bug
