### ISSUE TITLE
SQL Connection Fails on Initial Run

### ISSUE THREAD

**Issue by khatfull** [hashview/hashview#109] opened 2023-03-31 03:21 UTC
Greetings,

Installed Ubuntu server 20.04.3.  Installed hashview exactly per the installation guide here at GitHub.

Got everything installed but haven't been able to connect the hashview user to MySQL when starting hashview.  Ends with an error:

![error1](https://user-images.githubusercontent.com/28155128/229013549-81890465-6668-4131-a00a-4575f4db492e.jpg)

I can login to the MySQL command line with the same user and password (cut and pasted from config.conf), can see the user, can show databases, and use the hashview DB.

![mysql](https://user-images.githubusercontent.com/28155128/229013676-5eddfc8c-9d91-48a7-a8b5-a1fe358aef36.jpg)

No tables because hashview.py has never been successful.

Here's the config.conf (worrying about SMTP later):

![image](https://user-images.githubusercontent.com/28155128/229014123-58cb055d-946a-44fa-8e48-c6d7e47f14bc.png)

I've searched for the sqlalchemy error and can't seem to find anything that fits the case.

Any ideas?  Thanks!

**Comment by khatfull** [comment] 2023-03-31 14:33
Any FYI....

![image](https://user-images.githubusercontent.com/28155128/229149979-6db8f38e-1a81-4fcb-8366-616bf25a8250.png)

**Comment by johnburris** [comment] 2023-04-01 19:04
I am experiencing the exact same issue on Ubuntu 22.04.2

`sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1045 (28000): Access denied for user 'hashview'@'localhost' (using password: YES)
(Background on this error at: https://sqlalche.me/e/20/f405)`

**Comment by ralphte** [comment] 2023-04-02 20:11
Same here. Repeat #108

**Comment by khatfull** [comment] 2023-04-02 20:13
Thanks for chiming in guys.  Hopefully the devs can give us something to try.  I'm betting it's something really simple.

**Comment by i128** [comment] 2023-04-06 14:35
Sorry for the late replies. I'll have some dedicated time to look into this here in the next couple of days. I dont see off hand how this is happening so my next step is to see if i can replicate locally. I appreciate the error messages, and OS info. That should give me enough to start with.

**Comment by khatfull** [comment] 2023-04-06 15:20
Much obliged, much appreciated.  Thanks!  I'll drop the full stack trace below when I run hashview.py

**Comment by darkiron71** [comment] 2023-04-07 21:51
Experiencing the same issue as @khatfull. Attempted to install hashview exactly as per the instruction in the how-to. Unable to proceed until the issue is resolved.

**Comment by i128** [comment] 2023-05-01 02:50
I got some time this week and will be working on it.

**Comment by i128** [comment] 2023-05-01 14:25
Okay, can confirm its currently working in the following setup:
```
OS: Ubuntu 20.04.4 LTS
Python version: 3.8.10
Pip versions:

Flask==1.1.1
Flask-WTF==1.0.0
email-validator==1.1.3
Flask-SQLAlchemy==2.5.1
mysql-connector-python==8.0.27
Bcrypt-Flask==1.0.2
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==3.1.0
Flask-Script==2.0.6
Flask-APScheduler==1.12.2
WTForms-SQLAlchemy==0.3
packaging==21.3
Authlib==1.0.0
requests==2.22.0
```

This is just for placeholder info until i try upgrading python modules/python until i can recreate the error

**Comment by i128** [comment] 2023-05-01 14:30
Upgraded to latest modules, and app still runs.  Going to do a fresh install to see if i can recreate.

```
int128@hashview:~/hashview$ pip install --upgrade -r requirements.txt 
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/home/int128/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/x509.py:14: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
Collecting flask
  Downloading Flask-2.3.1-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 5.9 MB/s 
Collecting flask-wtf
  Downloading Flask_WTF-1.1.1-py3-none-any.whl (12 kB)
Collecting email_validator
  Downloading email_validator-2.0.0.post2-py3-none-any.whl (31 kB)
Collecting flask-sqlalchemy
  Downloading Flask_SQLAlchemy-3.0.3-py3-none-any.whl (24 kB)
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.33-cp38-cp38-manylinux1_x86_64.whl (27.4 MB)
     |████████████████████████████████| 27.4 MB 11.3 MB/s 
Requirement already up-to-date: bcrypt-flask in /home/int128/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.0.2)
Collecting flask-login
  Downloading Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Requirement already up-to-date: flask-mail in /home/int128/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (0.9.1)
Collecting flask-migrate
  Downloading Flask_Migrate-4.0.4-py3-none-any.whl (20 kB)
Requirement already up-to-date: flask-script in /home/int128/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.0.6)
Collecting flask-apscheduler
  Downloading Flask-APScheduler-1.12.4.tar.gz (12 kB)
Requirement already up-to-date: WTForms-SQLAlchemy in /home/int128/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (0.3)
Collecting packaging
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 7.8 MB/s 
Collecting authlib
  Downloading Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
     |████████████████████████████████| 214 kB 12.4 MB/s 
Collecting requests
  Downloading requests-2.29.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 2.4 MB/s 
Collecting importlib-metadata>=3.6.0; python_version < "3.10"
  Downloading importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting blinker>=1.6.2
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting click>=8.1.3
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 8.2 MB/s 
Collecting itsdangerous>=2.1.2
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Werkzeug>=2.3.0
  Downloading Werkzeug-2.3.2-py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 11.5 MB/s 
Collecting Jinja2>=3.1.2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 12.3 MB/s 
Requirement already satisfied, skipping upgrade: WTForms in /home/int128/.local/lib/python3.8/site-packages (from flask-wtf->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied, skipping upgrade: idna>=2.0.0 in /usr/lib/python3/dist-packages (from email_validator->-r requirements.txt (line 3)) (2.8)
Requirement already satisfied, skipping upgrade: dnspython>=2.0.0 in /home/int128/.local/lib/python3.8/site-packages (from email_validator->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied, skipping upgrade: SQLAlchemy>=1.4.18 in /home/int128/.local/lib/python3.8/site-packages (from flask-sqlalchemy->-r requirements.txt (line 4)) (1.4.27)
Requirement already satisfied, skipping upgrade: protobuf<=3.20.3,>=3.11.0 in /home/int128/.local/lib/python3.8/site-packages (from mysql-connector-python->-r requirements.txt (line 5)) (3.19.1)
Requirement already satisfied, skipping upgrade: bcrypt>=3.1.1 in /home/int128/.local/lib/python3.8/site-packages (from bcrypt-flask->-r requirements.txt (line 6)) (3.2.0)
Collecting alembic>=1.9.0
  Downloading alembic-1.10.4-py3-none-any.whl (212 kB)
     |████████████████████████████████| 212 kB 11.4 MB/s 
Requirement already satisfied, skipping upgrade: apscheduler<4.0.0,>=3.2.0 in /home/int128/.local/lib/python3.8/site-packages (from flask-apscheduler->-r requirements.txt (line 11)) (3.8.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.4.2 in /home/int128/.local/lib/python3.8/site-packages (from flask-apscheduler->-r requirements.txt (line 11)) (2.8.2)
Requirement already satisfied, skipping upgrade: cryptography>=3.2 in /home/int128/.local/lib/python3.8/site-packages (from authlib->-r requirements.txt (line 14)) (36.0.2)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 15)) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 15)) (2019.11.28)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
     |████████████████████████████████| 195 kB 11.3 MB/s 
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/int128/.local/lib/python3.8/site-packages (from importlib-metadata>=3.6.0; python_version < "3.10"->flask->-r requirements.txt (line 1)) (3.6.0)
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Requirement already satisfied, skipping upgrade: greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))) in /home/int128/.local/lib/python3.8/site-packages (from SQLAlchemy>=1.4.18->flask-sqlalchemy->-r requirements.txt (line 4)) (1.1.2)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in /usr/lib/python3/dist-packages (from bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (1.14.0)
Requirement already satisfied, skipping upgrade: cffi>=1.1 in /home/int128/.local/lib/python3.8/site-packages (from bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (1.15.0)
Collecting typing-extensions>=4
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Requirement already satisfied, skipping upgrade: Mako in /home/int128/.local/lib/python3.8/site-packages (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9)) (1.1.6)
Requirement already satisfied, skipping upgrade: importlib-resources; python_version < "3.9" in /home/int128/.local/lib/python3.8/site-packages (from alembic>=1.9.0->flask-migrate->-r requirements.txt (line 9)) (5.4.0)
Requirement already satisfied, skipping upgrade: pytz in /home/int128/.local/lib/python3.8/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (2021.3)
Requirement already satisfied, skipping upgrade: setuptools>=0.7 in /usr/lib/python3/dist-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (45.2.0)
Requirement already satisfied, skipping upgrade: tzlocal!=3.*,>=2.0 in /home/int128/.local/lib/python3.8/site-packages (from apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (4.1)
Requirement already satisfied, skipping upgrade: pycparser in /home/int128/.local/lib/python3.8/site-packages (from cffi>=1.1->bcrypt>=3.1.1->bcrypt-flask->-r requirements.txt (line 6)) (2.21)
Requirement already satisfied, skipping upgrade: pytz-deprecation-shim in /home/int128/.local/lib/python3.8/site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (0.1.0.post0)
Requirement already satisfied, skipping upgrade: backports.zoneinfo; python_version < "3.9" in /home/int128/.local/lib/python3.8/site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (0.2.1)
Requirement already satisfied, skipping upgrade: tzdata; python_version >= "3.6" in /home/int128/.local/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.2.0->flask-apscheduler->-r requirements.txt (line 11)) (2021.5)
Building wheels for collected packages: flask-apscheduler
  Building wheel for flask-apscheduler (setup.py) ... done
  Created wheel for flask-apscheduler: filename=Flask_APScheduler-1.12.4-py3-none-any.whl size=15725 sha256=38a1944c9e5f0d386be9ce8a21215caadf4f9ffd594631168c4044e4a6406fbd
  Stored in directory: /home/int128/.cache/pip/wheels/83/89/54/0f51ff73f88b28b6d0af3dad42efed206c732fd5edec3fcb08
Successfully built flask-apscheduler
Installing collected packages: importlib-metadata, blinker, click, itsdangerous, MarkupSafe, Werkzeug, Jinja2, flask, flask-wtf, email-validator, flask-sqlalchemy, mysql-connector-python, flask-login, typing-extensions, alembic, flask-migrate, flask-apscheduler, packaging, authlib, charset-normalizer, requests
  Attempting uninstall: flask-wtf
    Found existing installation: Flask-WTF 1.0.0
    Uninstalling Flask-WTF-1.0.0:
      Successfully uninstalled Flask-WTF-1.0.0
  Attempting uninstall: email-validator
    Found existing installation: email-validator 1.1.3
    Uninstalling email-validator-1.1.3:
      Successfully uninstalled email-validator-1.1.3
  Attempting uninstall: flask-sqlalchemy
    Found existing installation: Flask-SQLAlchemy 2.5.1
    Uninstalling Flask-SQLAlchemy-2.5.1:
      Successfully uninstalled Flask-SQLAlchemy-2.5.1
  Attempting uninstall: mysql-connector-python
    Found existing installation: mysql-connector-python 8.0.27
    Uninstalling mysql-connector-python-8.0.27:
      Successfully uninstalled mysql-connector-python-8.0.27
  Attempting uninstall: flask-login
    Found existing installation: Flask-Login 0.5.0
    Uninstalling Flask-Login-0.5.0:
      Successfully uninstalled Flask-Login-0.5.0
  Attempting uninstall: alembic
    Found existing installation: alembic 1.7.5
    Uninstalling alembic-1.7.5:
      Successfully uninstalled alembic-1.7.5
  Attempting uninstall: flask-migrate
    Found existing installation: Flask-Migrate 3.1.0
    Uninstalling Flask-Migrate-3.1.0:
      Successfully uninstalled Flask-Migrate-3.1.0
  Attempting uninstall: flask-apscheduler
    Found existing installation: Flask-APScheduler 1.12.2
    Uninstalling Flask-APScheduler-1.12.2:
      Successfully uninstalled Flask-APScheduler-1.12.2
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: authlib
    Found existing installation: Authlib 1.0.0
    Uninstalling Authlib-1.0.0:
      Successfully uninstalled Authlib-1.0.0
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.2 Werkzeug-2.3.2 alembic-1.10.4 authlib-1.2.0 blinker-1.6.2 charset-normalizer-3.1.0 click-8.1.3 email-validator-2.0.0.post2 flask-2.3.1 flask-apscheduler-1.12.4 flask-login-0.6.2 flask-migrate-4.0.4 flask-sqlalchemy-3.0.3 flask-wtf-1.1.1 importlib-metadata-6.6.0 itsdangerous-2.1.2 mysql-connector-python-8.0.33 packaging-23.1 requests-2.29.0 typing-extensions-4.5.0


int128@hashview:~/hashview$ python3 ./hashview.py 
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
✓ Admin user exists in database.
✓ Settings exist in database.
✓ Dynamic Wordlist exist in database. Count(1)
✓ Static Wordlist exist in database. Count(1)
✓ Rules exist in database. Count(1)
✓ Tasks exist in database. Count(3)
Done! Running Hashview! Enjoy.
/home/int128/.local/lib/python3.8/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
/home/int128/.local/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
 * Serving Flask app 'hashview'
 * Debug mode: off
```

**Comment by i128** [comment] 2023-05-01 18:00
I've been able to replicate this issue and have narrowed it down a bit:

On new installs, sqlalchemy doesnt appear to pass the user supplied password:
printing value of `cnx_kwargs` from <libpath>/python3.8/site-packages/mysql/connector/connection_cext.py ~ line 291

### On old install / upgrade
```
debug: {'host': 'localhost', 'user': 'hashview', 'password': 'DoNotUseThisPassword123!', 'password1': '', 'password2': '', 'password3': '', 'database': 'hashview', 'port': 3306, 'client_flags': 1286671, 'unix_socket': None, 'compress': False, 'ssl_disabled': False, 'conn_attrs': {'_connector_name': 'mysql-connector-python', '_connector_license': 'GPL-2.0', '_connector_version': '8.0.33', '_source_host': 'hashview'}, 'local_infile': False, 'load_data_local_dir': None, 'oci_config_file': None, 'oci_config_profile': None, 'fido_callback': None, 'ssl_ca': None, 'ssl_cert': None, 'ssl_key': None, 'ssl_cipher_suites': None, 'tls_versions': None, 'tls_cipher_suites': None, 'ssl_verify_cert': False, 'ssl_verify_identity': False}
```

### on new installs 
```
debug: {'host': 'localhost', 'user': 'hashview', 'password': '***', 'password1': '', 'password2': '', 'password3': '', 'database': 'hashview', 'port': 3306, 'client_flags': 1286671, 'unix_socket': None, 'compress': False, 'ssl_disabled': False, 'conn_attrs': {'_connector_name': 'mysql-connector-python', '_connector_license': 'GPL-2.0', '_connector_version': '8.0.33', '_source_host': 'hashview-debug'}, 'local_infile': False, 'load_data_local_dir': None, 'oci_config_file': None, 'oci_config_profile': None, 'fido_callback': None, 'ssl_ca': None, 'ssl_cert': None, 'ssl_key': None, 'ssl_cipher_suites': None, 'tls_versions': None, 'tls_cipher_suites': None, 'ssl_verify_cert': False, 'ssl_verify_identity': False}
```

in both cases the version of sqlalchemy is the same 🙃 . I've swapped out connectors too, (from mysqlconnector to mysqldb), and in both cases the passed value for the password is `***`.  

going to keep digging.

**Comment by i128** [comment] 2023-05-01 18:04
okay, for all yall that's running into this try the following:

```
python3 -m pip uninstall sqlalchemy
python3 -m pip install sqlalchemy==1.4.27
python3 ./hashview.py --debug
```

**Comment by khatfull** [comment] 2023-05-02 01:19
Happy to report it worked for me, I'm in the GUI now!!

I figured it was the sqlalchemy piece...the errors pointed in that direction but any more troubleshooting was beyond my means :)

Thank you SO much, project can now continue!

**Comment by khatfull** [comment] 2023-05-03 17:00
Just FYI, we're going to give the distributed cracking a big run for its money.  We have two boxes currently operating, one 2 x 2080Ti, one 2 x 1080Ti, and a third coming online with 3 x 3080Ti (as soon as a 44 lane CPU arrives).  Plan is to run the new machine as the first hashview agent, then reinstall and bring the others online as hashview agents.  I already dumped the hashes and passwords form the two old boxes to "import" them to the new hashview database by running a single crack job.  Should be fun and we're anxious to see some speeds.  Next machine is going to be mining rig based though.  Cases, even good ones, are too limiting above 3 cards.  Thanks again @i128 for getting us a resolution.

**Comment by i128** [comment] 2023-08-18 15:40
Fixed in https://github.com/hashview/hashview/commit/a4c15357629a9ac4a23c1a804509fa36dd33357a

will keep open until v0.8.1 lands

**Closed** 2023-08-19 00:54 UTC
Labels: bug
